//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_Free_Text
    {
        public int AnswerFreeText_ID { get; set; }
        public int Answer_ID { get; set; }
        public string Answer_Text { get; set; }
    
        public virtual Question_Answer Question_Answer { get; set; }
    }
}
