//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Available_Answer
    {
        public int AvailableAnswer_ID { get; set; }
        public string Answer { get; set; }
        public int Order_By { get; set; }
        public bool Active { get; set; }
    }
}
