//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampSubStep
    {
        public int SubStepID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StepID { get; set; }
        public string SubStepContent { get; set; }
    
        public virtual CampStep CampStep { get; set; }
    }
}
