//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredCheckerAnswer
    {
        public int CCAID { get; set; }
        public Nullable<int> CCID { get; set; }
        public Nullable<int> CCCID { get; set; }
    
        public virtual CredChecker CredChecker { get; set; }
        public virtual CredCheckerChoice CredCheckerChoice { get; set; }
    }
}
