//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredCheckerQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CredCheckerQuestion()
        {
            this.CredCheckerChoices = new HashSet<CredCheckerChoice>();
        }
    
        public int CCQID { get; set; }
        public string Question { get; set; }
        public Nullable<int> QuestionNumber { get; set; }
        public Nullable<int> ParentQID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CredCheckerChoice> CredCheckerChoices { get; set; }
    }
}
