//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainPoint()
        {
            this.SpeechMainPoints = new HashSet<SpeechMainPoint>();
        }
    
        public int MainPointID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> StrategyID { get; set; }
    
        public virtual Strategy Strategy { get; set; }
        public virtual Strategy Strategy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechMainPoint> SpeechMainPoints { get; set; }
    }
}
