//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Point
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Main_Point()
        {
            this.Main_Point_Transition = new HashSet<Main_Point_Transition>();
        }
    
        public int MainPoint_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Speech_ID { get; set; }
        public int OrgStrategy_ID { get; set; }
        public int Order_By { get; set; }
        public System.DateTime Entered_Date { get; set; }
        public System.DateTime Updated_Date { get; set; }
    
        public virtual Speech Speech { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Main_Point_Transition> Main_Point_Transition { get; set; }
        public virtual Organizational_Strategy Organizational_Strategy { get; set; }
    }
}
