//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMedia
    {
        public int MemberMediaID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string Path { get; set; }
        public Nullable<bool> PrimaryPic { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
