//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Carts = new HashSet<Cart>();
            this.Courses = new HashSet<Course>();
            this.MemberMedias = new HashSet<MemberMedia>();
            this.Purchases = new HashSet<Purchase>();
            this.Speeches = new HashSet<Speech>();
            this.MemberTicks = new HashSet<MemberTick>();
            this.MemberAssesses = new HashSet<MemberAssess>();
        }
    
        public int MemberID { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitial { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string AnxietyLevel { get; set; }
        public Nullable<int> ExperienceLevel { get; set; }
        public string FirstExperience { get; set; }
        public string SpeakerStrengths { get; set; }
        public string SpeakerPhysicalTicks { get; set; }
        public string ThreeCommunicationGoals { get; set; }
        public string AboutMe { get; set; }
        public string HighSchool { get; set; }
        public string HSGradYear { get; set; }
        public string University { get; set; }
        public string UGradYear { get; set; }
        public string FavJob { get; set; }
        public string FavJobWhy { get; set; }
        public string ProfilePic { get; set; }
        public string Location { get; set; }
        public string State { get; set; }
        public Nullable<int> HighestEducationID { get; set; }
        public string MostMemorableStory { get; set; }
        public Nullable<bool> CanShare { get; set; }
        public Nullable<bool> Anonymous { get; set; }
        public Nullable<int> MemberTypeID { get; set; }
        public Nullable<int> InstitutionID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Gender Gender1 { get; set; }
        public virtual HighestEducation HighestEducation { get; set; }
        public virtual Institution Institution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberMedia> MemberMedias { get; set; }
        public virtual Member Members1 { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual MemberType MemberType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Speech> Speeches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberTick> MemberTicks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberAssess> MemberAssesses { get; set; }
    }
}
