//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAssess
    {
        public int MemberAssessID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> AssessID { get; set; }
        public Nullable<bool> Strength { get; set; }
        public Nullable<bool> Weakness { get; set; }
        public Nullable<bool> Unknown { get; set; }
    
        public virtual Assess Assess { get; set; }
        public virtual Member Member { get; set; }
    }
}
