//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SpeechSageDBEntities : DbContext
    {
        public SpeechSageDBEntities()
            : base("name=SpeechSageDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CampStep> CampSteps { get; set; }
        public virtual DbSet<CampSubStep> CampSubSteps { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cart_Items> Cart_Items { get; set; }
        public virtual DbSet<Catalog> Catalogs { get; set; }
        public virtual DbSet<Catalog_Items> Catalog_Items { get; set; }
        public virtual DbSet<ConnectionType> ConnectionTypes { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CredChecker> CredCheckers { get; set; }
        public virtual DbSet<CredCheckerAnswer> CredCheckerAnswers { get; set; }
        public virtual DbSet<CredCheckerChoice> CredCheckerChoices { get; set; }
        public virtual DbSet<CredCheckerQuestion> CredCheckerQuestions { get; set; }
        public virtual DbSet<File_Type> File_Type { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<HighestEducation> HighestEducations { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<MainPoint> MainPoints { get; set; }
        public virtual DbSet<Medium> Media { get; set; }
        public virtual DbSet<MemberMedia> MemberMedias { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberType> MemberTypes { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<qAnswer> qAnswers { get; set; }
        public virtual DbSet<qChoice> qChoices { get; set; }
        public virtual DbSet<qChoiceType> qChoiceTypes { get; set; }
        public virtual DbSet<qQuestionChoice> qQuestionChoices { get; set; }
        public virtual DbSet<qQuestion> qQuestions { get; set; }
        public virtual DbSet<qSub_Step_Question> qSub_Step_Question { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<SourceType> SourceTypes { get; set; }
        public virtual DbSet<Speech> Speeches { get; set; }
        public virtual DbSet<SpeechMainPoint> SpeechMainPoints { get; set; }
        public virtual DbSet<SpeechStrategy> SpeechStrategies { get; set; }
        public virtual DbSet<SpeechSubpointConnection> SpeechSubpointConnections { get; set; }
        public virtual DbSet<SpeechSubpointResearch> SpeechSubpointResearches { get; set; }
        public virtual DbSet<SpeechSubpointResearchSummary> SpeechSubpointResearchSummaries { get; set; }
        public virtual DbSet<SpeechSubPoint> SpeechSubPoints { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<Strategy> Strategies { get; set; }
        public virtual DbSet<StrategyCategory> StrategyCategories { get; set; }
        public virtual DbSet<StrategySubCategory> StrategySubCategories { get; set; }
        public virtual DbSet<Sub_Step> Sub_Step { get; set; }
        public virtual DbSet<SubStepStatu> SubStepStatus { get; set; }
        public virtual DbSet<Transition> Transitions { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<Available_Answer> Available_Answer { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vwAnswer> vwAnswers { get; set; }
        public virtual DbSet<vwAnswersFull> vwAnswersFulls { get; set; }
        public virtual DbSet<vwCheckSubStep> vwCheckSubSteps { get; set; }
        public virtual DbSet<vwCheckSubStepsWithoutQuestion> vwCheckSubStepsWithoutQuestions { get; set; }
        public virtual DbSet<vwCompleteSpeechStep> vwCompleteSpeechSteps { get; set; }
        public virtual DbSet<vwIncompleteSpeechStep> vwIncompleteSpeechSteps { get; set; }
        public virtual DbSet<vwMainPoints_SubPoints> vwMainPoints_SubPoints { get; set; }
        public virtual DbSet<vwQuestionChoice> vwQuestionChoices { get; set; }
        public virtual DbSet<vwQuestionChoicesFull> vwQuestionChoicesFulls { get; set; }
        public virtual DbSet<vwQuestion> vwQuestions { get; set; }
        public virtual DbSet<vwSpeechMainPoint> vwSpeechMainPoints { get; set; }
        public virtual DbSet<vwStepsDetail> vwStepsDetails { get; set; }
        public virtual DbSet<vwSubStepsWithQuestion> vwSubStepsWithQuestions { get; set; }
        public virtual DbSet<vwUnansweredSubStep> vwUnansweredSubSteps { get; set; }
        public virtual DbSet<MemberTick> MemberTicks { get; set; }
        public virtual DbSet<Tick> Ticks { get; set; }
        public virtual DbSet<TickType> TickTypes { get; set; }
        public virtual DbSet<Assess> Assesses { get; set; }
        public virtual DbSet<AssessType> AssessTypes { get; set; }
        public virtual DbSet<MemberAssess> MemberAssesses { get; set; }
        public virtual DbSet<BillingAddress> BillingAddresses { get; set; }
        public virtual DbSet<BillingCard> BillingCards { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<PromoCode> PromoCodes { get; set; }
        public virtual DbSet<AnxietyQuestion> AnxietyQuestions { get; set; }
        public virtual DbSet<SpeechSlideSave> SpeechSlideSaves { get; set; }
    
        public virtual ObjectResult<spGetUnansweredSteps_Result> spGetUnansweredSteps(Nullable<int> speechID)
        {
            var speechIDParameter = speechID.HasValue ?
                new ObjectParameter("speechID", speechID) :
                new ObjectParameter("speechID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUnansweredSteps_Result>("spGetUnansweredSteps", speechIDParameter);
        }
    
        public virtual int spIsStepComplete(Nullable<int> stepID)
        {
            var stepIDParameter = stepID.HasValue ?
                new ObjectParameter("StepID", stepID) :
                new ObjectParameter("StepID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spIsStepComplete", stepIDParameter);
        }
    
        public virtual ObjectResult<spGetUnansweredSteps1_Result> spGetUnansweredSteps1(Nullable<int> speechID)
        {
            var speechIDParameter = speechID.HasValue ?
                new ObjectParameter("speechID", speechID) :
                new ObjectParameter("speechID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUnansweredSteps1_Result>("spGetUnansweredSteps1", speechIDParameter);
        }
    }
}
