//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qAnswer
    {
        public int answerID { get; set; }
        public Nullable<int> questionChoiceID { get; set; }
        public Nullable<int> speechID { get; set; }
        public string free_text { get; set; }
    
        public virtual qQuestionChoice qQuestionChoice { get; set; }
        public virtual Speech Speech { get; set; }
    }
}
