//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qQuestionChoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qQuestionChoice()
        {
            this.qAnswers = new HashSet<qAnswer>();
        }
    
        public int questionChoiceID { get; set; }
        public Nullable<int> choiceID { get; set; }
        public Nullable<int> subStepQuestionID { get; set; }
        public Nullable<int> choiceTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qAnswer> qAnswers { get; set; }
        public virtual qChoice qChoice { get; set; }
        public virtual qChoiceType qChoiceType { get; set; }
        public virtual qSub_Step_Question qSub_Step_Question { get; set; }
    }
}
