//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qSub_Step_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qSub_Step_Question()
        {
            this.qQuestionChoices = new HashSet<qQuestionChoice>();
        }
    
        public int subStepQuestionID { get; set; }
        public Nullable<int> questionID { get; set; }
        public Nullable<int> subStep_ID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qQuestionChoice> qQuestionChoices { get; set; }
        public virtual qQuestion qQuestion { get; set; }
        public virtual Sub_Step Sub_Step { get; set; }
    }
}
