//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Answer
    {
        public int Answer_ID { get; set; }
        public int Speech_ID { get; set; }
        public int Question_ID { get; set; }
        public int AnswerType_ID { get; set; }
        public System.DateTime Entered_Date { get; set; }
        public System.DateTime Updated_Date { get; set; }
    }
}
