//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Source()
        {
            this.SpeechSubpointResearches = new HashSet<SpeechSubpointResearch>();
        }
    
        public int SourceID { get; set; }
        public string When { get; set; }
        public string Who { get; set; }
        public string What { get; set; }
        public Nullable<int> SpeechID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SourceTypeID { get; set; }
        public Nullable<decimal> CredScore { get; set; }
    
        public virtual SourceType SourceType { get; set; }
        public virtual Speech Speech { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechSubpointResearch> SpeechSubpointResearches { get; set; }
    }
}
