//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source_Reference_Event
    {
        public int Event_ID { get; set; }
        public int Speech_ID { get; set; }
        public string Year { get; set; }
        public string People { get; set; }
        public string KeyPoints { get; set; }
        public System.DateTime Entered_Date { get; set; }
        public System.DateTime Updated_Date { get; set; }
    
        public virtual Speech Speech { get; set; }
    }
}
