//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source_Reference_Research
    {
        public int Research_ID { get; set; }
        public Nullable<int> Speech_ID { get; set; }
        public string Author { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
        public string Publication_Source { get; set; }
        public string Reference_Text { get; set; }
        public string Pages_Set { get; set; }
        public System.DateTime Entered_Date { get; set; }
        public System.DateTime Updated_Date { get; set; }
    
        public virtual Speech Speech { get; set; }
    }
}
