//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeechMainPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpeechMainPoint()
        {
            this.SpeechSubPoints = new HashSet<SpeechSubPoint>();
        }
    
        public int SpeechMainPointID { get; set; }
        public Nullable<int> MainPointID { get; set; }
        public string MainPointFreeText { get; set; }
        public Nullable<int> SpeechID { get; set; }
        public Nullable<int> Ordinal { get; set; }
    
        public virtual MainPoint MainPoint { get; set; }
        public virtual Speech Speech { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechSubPoint> SpeechSubPoints { get; set; }
    }
}
