//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech_Organizational_Strategy
    {
        public int ID { get; set; }
        public int Speech_ID { get; set; }
        public int OrgStrategy_ID { get; set; }
        public bool Selected { get; set; }
        public System.DateTime Entered_Date { get; set; }
    
        public virtual Organizational_Strategy Organizational_Strategy { get; set; }
        public virtual Speech Speech { get; set; }
    }
}
