//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeechSubPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpeechSubPoint()
        {
            this.SpeechSubpointConnections = new HashSet<SpeechSubpointConnection>();
            this.SpeechSubpointResearches = new HashSet<SpeechSubpointResearch>();
            this.SpeechSubpointResearchSummaries = new HashSet<SpeechSubpointResearchSummary>();
        }
    
        public int SpeechSubPointsID { get; set; }
        public Nullable<int> SpeechMainPointID { get; set; }
        public Nullable<int> StrategyID { get; set; }
        public string SubPointFreeText { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public Nullable<int> TransitionID { get; set; }
        public string TransitionText { get; set; }
    
        public virtual SpeechMainPoint SpeechMainPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechSubpointConnection> SpeechSubpointConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechSubpointResearch> SpeechSubpointResearches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechSubpointResearchSummary> SpeechSubpointResearchSummaries { get; set; }
        public virtual Strategy Strategy { get; set; }
        public virtual Transition Transition { get; set; }
    }
}
