//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Speech()
        {
            this.qAnswers = new HashSet<qAnswer>();
            this.Slides = new HashSet<Slide>();
            this.Sources = new HashSet<Source>();
            this.SpeechMainPoints = new HashSet<SpeechMainPoint>();
            this.SpeechStrategies = new HashSet<SpeechStrategy>();
            this.SubStepStatus = new HashSet<SubStepStatu>();
            this.SpeechSlideSaves = new HashSet<SpeechSlideSave>();
        }
    
        public int Speech_ID { get; set; }
        public string Topic { get; set; }
        public Nullable<int> CitationStyle_ID { get; set; }
        public Nullable<int> OrgType_ID { get; set; }
        public Nullable<int> Research_Total { get; set; }
        public System.DateTime Entered_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Filename { get; set; }
        public int memberID { get; set; }
        public Nullable<int> courseID { get; set; }
        public string courseName { get; set; }
        public string instrEmail { get; set; }
        public string Notes { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qAnswer> qAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slide> Slides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Source> Sources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechMainPoint> SpeechMainPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechStrategy> SpeechStrategies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubStepStatu> SubStepStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpeechSlideSave> SpeechSlideSaves { get; set; }
    }
}
