//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int tokenLinkID { get; set; }
        public string token1 { get; set; }
        public bool used { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> usedDate { get; set; }
        public Nullable<int> memberID { get; set; }
    }
}
