//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMainPoints_SubPoints
    {
        public Nullable<int> SpeechID { get; set; }
        public int SpeechMainPointID { get; set; }
        public Nullable<int> MainPointID { get; set; }
        public string MainPointFreeText { get; set; }
        public Nullable<int> OrdMP { get; set; }
        public Nullable<int> SpeechSubPointsID { get; set; }
        public Nullable<int> StrategyID { get; set; }
        public string SubPointFreeText { get; set; }
        public Nullable<int> TransitionID { get; set; }
        public string Trans { get; set; }
        public string Trans_Txt { get; set; }
        public Nullable<int> OrdSP { get; set; }
        public string When { get; set; }
        public string Who { get; set; }
        public string What { get; set; }
        public string SummaryText { get; set; }
        public string CnnType { get; set; }
        public string ConnectionTxt { get; set; }
    }
}
