//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwQuestionChoicesFull
    {
        public int Step_ID { get; set; }
        public Nullable<int> subStep_ID { get; set; }
        public Nullable<int> subStepQuestionID { get; set; }
        public int questionChoiceID { get; set; }
        public string Choice { get; set; }
        public string Choice_Type { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
