//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC_EmailConf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSpeechMainPoint
    {
        public int SpeechMainPointID { get; set; }
        public Nullable<int> MainPointID { get; set; }
        public string MainPointFreeText { get; set; }
        public Nullable<int> SpeechID { get; set; }
        public Nullable<int> Ordinal { get; set; }
    }
}
